"""
report.py — assemble a qualitative analysis report (DOCX) for client handoff.

The CSV export (schema.flatten_to_csv) is the STRUCTURED deliverable. This module
is the QUALITATIVE deliverable: a single, self-contained Word document a reviewer
can read or edit without opening the app. It combines, in order:

  1. Site identity (who / where / when)
  2. Overall recommendation (the narrative verdict)
  3. Key findings — habitats, species, legislation, mitigation, invasive species
     (rendered as readable tables, one section each)
  4. Figure captions (photo / map / diagram) if any were captioned
  5. Q&A transcript — the grounded questions asked in the session, with the
     model's section-cited answers

Everything here is drawn ONLY from content already extracted / generated by the
app (schema, ExtractedDoc, session Q&A history) — nothing new is inferred.

PROTOTYPE NOTE
--------------
DOCX is used because it is editable and matches the wider platform's export
convention (Lenders-QA uses python-docx). The production port can reuse this
assembler verbatim and, if a PDF is required, render the same DOCX to PDF.
"""

from __future__ import annotations

import io
from typing import Any, Dict, List, Tuple

from docx import Document
from docx.shared import Pt

import schema as schema_mod


# Human labels + the item keys to show, for each schema array field. Kept here
# (not imported from schema._ARRAY_FIELDS) so column order/labels in the client
# report can differ from the CSV without touching extraction logic.
_SECTIONS: List[Tuple[str, str, List[Tuple[str, str]]]] = [
    (
        "habitats_identified",
        "Habitats identified",
        [("habitat_type", "Habitat"), ("description", "Description"), ("bap_status", "BAP status")],
    ),
    (
        "species_assessed",
        "Species assessed",
        [
            ("species_group", "Species / group"),
            ("legal_protection", "Legal protection"),
            ("evidence_or_potential", "Evidence / potential"),
            ("recommended_action", "Recommended action"),
        ],
    ),
    (
        "legislation_cited",
        "Legislation cited",
        [
            ("act_or_regulation", "Act / regulation"),
            ("schedule_or_section", "Schedule / section"),
            ("protects", "Protects"),
        ],
    ),
    (
        "mitigation_measures",
        "Mitigation measures",
        [("measure", "Measure"), ("reason", "Reason")],
    ),
    (
        "invasive_species_flags",
        "Invasive species flags",
        [
            ("species", "Species"),
            ("location_on_site", "Location on site"),
            ("control_obligation", "Control obligation"),
        ],
    ),
]

_SITE_LABELS: List[Tuple[str, str]] = [
    ("site_name", "Site name"),
    ("location", "Location"),
    ("grid_reference", "Grid reference"),
    ("client", "Client"),
    ("surveyor", "Surveyor"),
    ("surveyor_credentials", "Surveyor credentials"),
    ("survey_date", "Survey date"),
]


def _add_kv_table(document: Document, rows: List[Tuple[str, str]]) -> None:
    """Two-column key/value table (used for site identity)."""
    table = document.add_table(rows=0, cols=2)
    table.style = "Light Grid Accent 1"
    for label, value in rows:
        cells = table.add_row().cells
        cells[0].text = label
        cells[1].text = value or "—"
        for para in cells[0].paragraphs:
            for run in para.runs:
                run.bold = True


def _add_items_table(
    document: Document, items: List[Dict[str, str]], columns: List[Tuple[str, str]]
) -> None:
    """Header-row table, one record per item, for a schema array field."""
    table = document.add_table(rows=1, cols=len(columns))
    table.style = "Light Grid Accent 1"
    for i, (_, label) in enumerate(columns):
        cell = table.rows[0].cells[i]
        cell.text = label
        for para in cell.paragraphs:
            for run in para.runs:
                run.bold = True
    for item in items:
        cells = table.add_row().cells
        for i, (key, _) in enumerate(columns):
            cells[i].text = str(item.get(key, "") or "—")


def make_report_docx(
    file_name: str,
    schema: Dict[str, Any],
    doc: Any,
    qa_history: List[Tuple[str, str]],
) -> bytes:
    """Build the qualitative analysis report and return it as DOCX bytes.

    `doc` is an extraction.ExtractedDoc (used for figure captions); `qa_history`
    is the session's list of (question, answer) pairs in most-recent-first order.
    """
    schema = schema or {}
    document = Document()

    # --- Title block --------------------------------------------------------
    document.add_heading("Environmental & Social Survey — Qualitative Analysis", level=0)
    subtitle = document.add_paragraph()
    run = subtitle.add_run(f"Source report: {file_name or '(unnamed)'}")
    run.italic = True
    run.font.size = Pt(11)

    # --- 1. Site identity ---------------------------------------------------
    document.add_heading("1. Site identity", level=1)
    site = schema.get("site_identity", {}) or {}
    _add_kv_table(document, [(label, str(site.get(key, "") or "")) for key, label in _SITE_LABELS])

    # --- 2. Overall recommendation ------------------------------------------
    document.add_heading("2. Overall recommendation", level=1)
    document.add_paragraph(schema.get("overall_recommendation") or "Not stated in the document.")

    # --- 3. Key findings -----------------------------------------------------
    document.add_heading("3. Key findings", level=1)
    n = 0
    for field, label, columns in _SECTIONS:
        items = schema.get(field, []) or []
        n += 1
        document.add_heading(f"3.{n} {label} ({len(items)})", level=2)
        if items:
            _add_items_table(document, items, columns)
        else:
            document.add_paragraph("None identified in the document.")

    # --- 4. Figures ----------------------------------------------------------
    figures = getattr(doc, "figures", []) or []
    captioned = [f for f in figures if getattr(f, "caption", "")]
    if captioned:
        document.add_heading("4. Figures", level=1)
        for fig in captioned:
            tag = f" [{fig.category}]" if getattr(fig, "category", "") else ""
            document.add_paragraph(
                f"Figure {fig.index} (p.{fig.page}){tag}: {fig.caption}",
                style="List Bullet",
            )

    # --- 5. Q&A transcript ---------------------------------------------------
    if qa_history:
        document.add_heading("5. Q&A transcript", level=1)
        # Show in asked order (session stores most-recent-first).
        for question, answer in reversed(qa_history):
            q = document.add_paragraph()
            q.add_run("Q: ").bold = True
            q.add_run(question)
            a = document.add_paragraph()
            a.add_run("A: ").bold = True
            a.add_run(answer)

    buf = io.BytesIO()
    document.save(buf)
    return buf.getvalue()
